library("dplyr")
library("lubridate")
#read the text file
PowerConsumptionData <- read.table("household_power_consumption.txt", sep=";",header = TRUE, stringsAsFactors=FALSE)
#using dmy from lubridate package to convert Date/Time class instead of as.Date
DateRange1<- dmy("01/02/2007")
DateRange2<- dmy("02/02/2007")
#subset the data only for two days (01/02/2007-02/02/2007)
PowerConsumptionDataSubset <- filter(PowerConsumptionData, dmy(Date) >= DateRange1 & dmy(Date) <= DateRange2)
DateTime <- dmy_hms(paste(PowerConsumptionDataSubset$Date, PowerConsumptionDataSubset$Time, sep=" "))
SubMetering_1 <- as.numeric(PowerConsumptionDataSubset$Sub_metering_1)
SubMetering_2 <- as.numeric(PowerConsumptionDataSubset$Sub_metering_2)
SubMetering_3 <- as.numeric(PowerConsumptionDataSubset$Sub_metering_3)
png("plot3.png", width=480, height=480)
par(mfrow = c(1, 1))
plot(DateTime, SubMetering_1, type="l", xlab="", ylab="Energy sub metering")
lines(DateTime, SubMetering_2, type="l", col="red")
lines(DateTime, SubMetering_3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"), lty=1, lwd= 1)
dev.off()
